### PR TITLE
v0.44.x compatibility

### PR DESCRIPTION
**Pull request by slvrtrn**
The driver was adjusted to work with the most recent Metabase versions.
Breaking changes introduced in 0.42.0+ were fixed.

Currently, the FK feature is disabled for tests (but should be enabled in GUI to do manual FKs) since many (30+) related tests were failing. We need to decide whether it makes sense to invest time in re-implementation or if we can keep it this way.

GitHub actions were updated to be used with the mainline Metabase repo. Unfixable tests were "ignored" (or, more precisely, only working tests were included) using [custom deps.edn](https://github.com/enqueue/metabase-clickhouse-driver/blob/02c5d03df2727f4e4c9683d12e8fb2ad0588d501/.github/deps.edn).

There is no need to hardcode `clickhouse` as a Metabase dependency anymore (like [here](https://github.com/enqueue/metabase/pull/5/files#diff-4f4fbe122f0f83e0834c3650bc5c236d35eb588c975e08102d04f9fa2e3aa3fcR4) and [here](https://github.com/enqueue/metabase/commit/3db4b62a4d8a7cfd89c0c3b43b05a5c9ffdb8ca4)) - I just added a few hacks in the GitHub actions

For building a driver just overwrite the entire drivers `deps.edn` ([it works](https://github.com/enqueue/metabase-clickhouse-driver/actions/runs/3456051745/jobs/5768511396#step:11:869), I just moved the JAR build beneath the tests for now): 
```sh
echo "{:deps {metabase/clickhouse {:local/root \"clickhouse\" }}}" > modules/drivers/deps.edn
bin/build-driver.sh clickhouse
```

JDBC driver will be updated after we merge this one.

Progress:
- [x] Fix breaking changes
- [x] Fix or ignore failings tests
- [x] Decide on FK

Resolves:
https://github.com/enqueue/metabase-clickhouse-driver/issues/105 
https://github.com/enqueue/metabase-clickhouse-driver/issues/101 
https://github.com/enqueue/metabase-clickhouse-driver/issues/97

Maybe also https://github.com/enqueue/metabase-clickhouse-driver/issues/100

### CODE REVIEW

**Comment by enqueue** [comment]
Thanks @slvrtrn Let's discuss the changes later this week.

**Comment by slvrtrn** [comment]
Green CI. I think we are ready.

**Comment by slvrtrn** [comment]
Re-enabled more tests. Only 3 test cases are blacklisted now (not the entire namespaces with 30+ test cases).

**Comment by enqueue** [comment]
Let's try this :smile:  Thanks @slvrtrn !

**Pull request merged**
